{
 "title": "Home",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU % use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"} + node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "HDD Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=~\"ext4|xfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 } }
 ]
}