apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        volumeMounts:
        - name: web-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-html
        configMap:
          name: env-config-test

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-test
data:
  index.html: |
    <html>
    <body>
      <h1>Welcome to nginx test v1.28</h1>
    </body>
    </html>

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx-test
  type: NodePort
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
