apiVersion: apps/v1
kind: Deployment
metadata:
  name: vol-deployment
  labels:
    app: vol
spec:
  selector:
    matchLabels:
      app: vol
  template:
    metadata:
      labels:
        app: vol
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'while true; do echo "$(date)">>/etc/out/test.txt;sleep 5;done']
        volumeMounts:
        - name: example-volume
          mountPath: /etc/out
      - name: multitool
        image: wbitt/network-multitool:latest
        volumeMounts:
        - name: example-volume
          mountPath: /etc/in
      volumes:
      - name: example-volume
        persistentVolumeClaim:
          claimName: example-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data"
