apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool-https-port
      protocol: TCP
      port: 443
      targetPort: 443
    - name: multitool-http-port
      protocol: TCP
      port: 1180
      targetPort: 1180
