apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-config
  namespace: atlantis
data:
  repos.yaml: |
    repos:
      - id: /.*/
        branch: /.*/
        allowed_overrides: [apply_requirements]
        apply_requirements: [approved]
        workflow: default

  atlantis.yaml: |
    workflows:
      default:
        plan:
          steps:
            - init
            - plan
        apply:
          steps:
            - apply
