apiVersion: v1
kind: Service
metadata:
  name: svc-np
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx-np
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-np
      protocol: TCP
      port: 9002
      targetPort: 8080
