apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
  namespace: app
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
