apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: nginx-np
      protocol: TCP
      port: 80
      targetPort: 80
